"""Object storage with two interchangeable backends.

MinIO/S3 is the real path. The local-filesystem backend exists so the app
still runs if someone clones the repo without Docker — the interface is
identical, so nothing downstream knows which is active.

Keys are always generated by security.filenames.build_storage_key; this module
never accepts a caller-supplied path.
"""

from __future__ import annotations

import logging
import re
from abc import ABC, abstractmethod
from pathlib import Path

import boto3
from botocore.client import Config
from botocore.exceptions import BotoCoreError, ClientError

from ..config import settings

logger = logging.getLogger(__name__)

# A storage key is only ever produced by build_storage_key. This guard makes a
# path-traversal key structurally impossible even if a caller misbehaves.
_SAFE_KEY = re.compile(r"^users/[0-9a-f-]{36}/uploads/[0-9a-f-]{36}/[A-Za-z0-9._-]+$")


class StorageError(Exception):
    pass


def _assert_safe_key(key: str) -> None:
    if not _SAFE_KEY.match(key):
        raise StorageError(f"Refusing to use unsafe storage key: {key!r}")


class Storage(ABC):
    @abstractmethod
    def put(self, key: str, data: bytes, content_type: str) -> None: ...

    @abstractmethod
    def get(self, key: str) -> bytes: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def delete_prefix(self, prefix: str) -> int: ...


class S3Storage(Storage):
    """MinIO locally, any S3-compatible service in production."""

    def __init__(self) -> None:
        self._client = boto3.client(
            "s3",
            endpoint_url=settings.s3_endpoint_url or None,
            aws_access_key_id=settings.s3_access_key,
            aws_secret_access_key=settings.s3_secret_key,
            region_name=settings.s3_region,
            config=Config(signature_version="s3v4", s3={"addressing_style": "path"}),
        )
        self._bucket = settings.s3_bucket
        self._ensure_bucket()

    def _ensure_bucket(self) -> None:
        """Confirm the bucket is usable, creating it only outside production.

        Auto-creation exists so `make up` produces a working MinIO bucket with
        no manual step. It is wrong in production twice over: the bucket is
        infrastructure that should already exist with its own lifecycle and
        retention policy, and a credential scoped to one bucket — the
        recommended shape for a Cloudflare R2 API token — has no CreateBucket
        permission, so attempting it turns a clear "bucket missing" into a
        confusing "access denied".
        """
        try:
            self._client.head_bucket(Bucket=self._bucket)
            return
        except (ClientError, BotoCoreError) as exc:
            if settings.is_production:
                raise StorageError(
                    f"Bucket {self._bucket!r} is not reachable with the configured "
                    "credentials. Check S3_ENDPOINT_URL, S3_BUCKET, S3_REGION and the "
                    "access key pair."
                ) from exc
            head_failure = exc

        try:
            self._client.create_bucket(Bucket=self._bucket)
            logger.info("Created bucket %s", self._bucket)
        except ClientError as exc:  # already exists / race
            if exc.response.get("Error", {}).get("Code") not in {
                "BucketAlreadyOwnedByYou",
                "BucketAlreadyExists",
            }:
                raise StorageError(f"Cannot create bucket {self._bucket}: {exc}") from exc
        except BotoCoreError as exc:
            # The endpoint is unreachable rather than the bucket being absent.
            raise StorageError(f"Cannot reach object storage: {head_failure}") from exc

    def put(self, key: str, data: bytes, content_type: str) -> None:
        _assert_safe_key(key)
        try:
            self._client.put_object(
                Bucket=self._bucket, Key=key, Body=data, ContentType=content_type
            )
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Upload failed: {exc}") from exc

    def get(self, key: str) -> bytes:
        _assert_safe_key(key)
        try:
            response = self._client.get_object(Bucket=self._bucket, Key=key)
            return response["Body"].read()
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Download failed: {exc}") from exc

    def delete(self, key: str) -> None:
        _assert_safe_key(key)
        try:
            self._client.delete_object(Bucket=self._bucket, Key=key)
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Delete failed: {exc}") from exc

    def delete_prefix(self, prefix: str) -> int:
        """Used by Settings -> Delete my data."""
        deleted = 0
        paginator = self._client.get_paginator("list_objects_v2")
        try:
            for page in paginator.paginate(Bucket=self._bucket, Prefix=prefix):
                keys = [{"Key": obj["Key"]} for obj in page.get("Contents", [])]
                if keys:
                    self._client.delete_objects(Bucket=self._bucket, Delete={"Objects": keys})
                    deleted += len(keys)
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Bulk delete failed: {exc}") from exc
        return deleted


class LocalStorage(Storage):
    """Filesystem fallback. Every write is confined under local_storage_dir."""

    def __init__(self) -> None:
        self._root = settings.local_storage_path
        self._root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        _assert_safe_key(key)
        path = (self._root / key).resolve()
        root = self._root.resolve()
        # Defence in depth: even with a validated key, never escape the root.
        if not path.is_relative_to(root):
            raise StorageError("Resolved path escaped the storage root")
        return path

    def put(self, key: str, data: bytes, content_type: str) -> None:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def get(self, key: str) -> bytes:
        path = self._resolve(key)
        if not path.exists():
            raise StorageError(f"Object not found: {key}")
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = self._resolve(key)
        path.unlink(missing_ok=True)

    def delete_prefix(self, prefix: str) -> int:
        base = (self._root / prefix).resolve()
        if not base.is_relative_to(self._root.resolve()) or not base.exists():
            return 0
        deleted = sum(1 for p in base.rglob("*") if p.is_file())
        for path in sorted(base.rglob("*"), reverse=True):
            path.unlink() if path.is_file() else path.rmdir()
        base.rmdir()
        return deleted


_storage: Storage | None = None


def reset_storage(storage: Storage | None = None) -> None:
    """Inject a backend, or clear the cached one. Used by tests.

    Mirrors security.ratelimit.reset_limiter: the singleton is chosen from
    settings on first use, so a test that varies STORAGE_BACKEND or
    ENVIRONMENT has to be able to discard it.
    """
    global _storage
    _storage = storage


def get_storage() -> Storage:
    """Process-wide storage singleton, chosen by STORAGE_BACKEND.

    The fallback to local disk is a **development** convenience: someone who
    cloned the repo without Docker still gets a working upload path.

    In production it would be silent data loss of the worst kind. The API and
    the worker are separate containers with separate filesystems, so falling
    back would have the API write a receipt to its own disk and the worker look
    for it on another — every OCR job failing with a missing file, every stored
    image unreadable, and the container's disk discarded on the next deploy.
    Nothing in the interface would report a problem, because from the
    application's point of view the write succeeded. Production fails loudly
    instead.
    """
    global _storage
    if _storage is None:
        if settings.storage_backend == "local":
            _storage = LocalStorage()
        else:
            try:
                _storage = S3Storage()
            except StorageError:
                if settings.is_production:
                    logger.critical(
                        "Object storage is unavailable and STORAGE_BACKEND is not "
                        "'local'. Refusing to fall back to container-local disk in "
                        "production: the API and worker do not share one."
                    )
                    raise
                logger.warning("MinIO/S3 unavailable — falling back to local storage")
                _storage = LocalStorage()
    return _storage
