"""Object storage with two interchangeable backends.

MinIO/S3 is the real path. The local-filesystem backend exists so the app
still runs if someone clones the repo without Docker — the interface is
identical, so nothing downstream knows which is active.

Keys are always generated by security.filenames.build_storage_key; this module
never accepts a caller-supplied path.
"""

from __future__ import annotations

import logging
import re
from abc import ABC, abstractmethod
from pathlib import Path

import boto3
from botocore.client import Config
from botocore.exceptions import BotoCoreError, ClientError

from ..config import settings

logger = logging.getLogger(__name__)

# A storage key is only ever produced by build_storage_key. This guard makes a
# path-traversal key structurally impossible even if a caller misbehaves.
_SAFE_KEY = re.compile(r"^users/[0-9a-f-]{36}/uploads/[0-9a-f-]{36}/[A-Za-z0-9._-]+$")


class StorageError(Exception):
    pass


def _assert_safe_key(key: str) -> None:
    if not _SAFE_KEY.match(key):
        raise StorageError(f"Refusing to use unsafe storage key: {key!r}")


class Storage(ABC):
    @abstractmethod
    def put(self, key: str, data: bytes, content_type: str) -> None: ...

    @abstractmethod
    def get(self, key: str) -> bytes: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def delete_prefix(self, prefix: str) -> int: ...


class S3Storage(Storage):
    """MinIO locally, any S3-compatible service in production."""

    def __init__(self) -> None:
        self._client = boto3.client(
            "s3",
            endpoint_url=settings.s3_endpoint_url or None,
            aws_access_key_id=settings.s3_access_key,
            aws_secret_access_key=settings.s3_secret_key,
            region_name=settings.s3_region,
            config=Config(signature_version="s3v4", s3={"addressing_style": "path"}),
        )
        self._bucket = settings.s3_bucket
        self._ensure_bucket()

    def _ensure_bucket(self) -> None:
        try:
            self._client.head_bucket(Bucket=self._bucket)
        except ClientError:
            try:
                self._client.create_bucket(Bucket=self._bucket)
                logger.info("Created bucket %s", self._bucket)
            except ClientError as exc:  # already exists / race
                if exc.response.get("Error", {}).get("Code") not in {
                    "BucketAlreadyOwnedByYou",
                    "BucketAlreadyExists",
                }:
                    raise StorageError(f"Cannot create bucket {self._bucket}: {exc}") from exc

    def put(self, key: str, data: bytes, content_type: str) -> None:
        _assert_safe_key(key)
        try:
            self._client.put_object(
                Bucket=self._bucket, Key=key, Body=data, ContentType=content_type
            )
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Upload failed: {exc}") from exc

    def get(self, key: str) -> bytes:
        _assert_safe_key(key)
        try:
            response = self._client.get_object(Bucket=self._bucket, Key=key)
            return response["Body"].read()
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Download failed: {exc}") from exc

    def delete(self, key: str) -> None:
        _assert_safe_key(key)
        try:
            self._client.delete_object(Bucket=self._bucket, Key=key)
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Delete failed: {exc}") from exc

    def delete_prefix(self, prefix: str) -> int:
        """Used by Settings -> Delete my data."""
        deleted = 0
        paginator = self._client.get_paginator("list_objects_v2")
        try:
            for page in paginator.paginate(Bucket=self._bucket, Prefix=prefix):
                keys = [{"Key": obj["Key"]} for obj in page.get("Contents", [])]
                if keys:
                    self._client.delete_objects(Bucket=self._bucket, Delete={"Objects": keys})
                    deleted += len(keys)
        except (ClientError, BotoCoreError) as exc:
            raise StorageError(f"Bulk delete failed: {exc}") from exc
        return deleted


class LocalStorage(Storage):
    """Filesystem fallback. Every write is confined under local_storage_dir."""

    def __init__(self) -> None:
        self._root = settings.local_storage_path
        self._root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        _assert_safe_key(key)
        path = (self._root / key).resolve()
        root = self._root.resolve()
        # Defence in depth: even with a validated key, never escape the root.
        if not path.is_relative_to(root):
            raise StorageError("Resolved path escaped the storage root")
        return path

    def put(self, key: str, data: bytes, content_type: str) -> None:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def get(self, key: str) -> bytes:
        path = self._resolve(key)
        if not path.exists():
            raise StorageError(f"Object not found: {key}")
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = self._resolve(key)
        path.unlink(missing_ok=True)

    def delete_prefix(self, prefix: str) -> int:
        base = (self._root / prefix).resolve()
        if not base.is_relative_to(self._root.resolve()) or not base.exists():
            return 0
        deleted = sum(1 for p in base.rglob("*") if p.is_file())
        for path in sorted(base.rglob("*"), reverse=True):
            path.unlink() if path.is_file() else path.rmdir()
        base.rmdir()
        return deleted


_storage: Storage | None = None


def get_storage() -> Storage:
    """Process-wide storage singleton, chosen by STORAGE_BACKEND."""
    global _storage
    if _storage is None:
        if settings.storage_backend == "local":
            _storage = LocalStorage()
        else:
            try:
                _storage = S3Storage()
            except StorageError:
                logger.warning("MinIO/S3 unavailable — falling back to local storage")
                _storage = LocalStorage()
    return _storage
