"""Reading transaction tables out of statement PDFs.

Every fixture is generated by `tests.synthetic_pdf`, never collected. The
guard test at the bottom asserts that, so a real statement cannot enter the
suite by accident.

The cases that matter most are the ones where being wrong is invisible: a
continuation page silently dropped makes a short month look like a complete
one, and a sign taken on trust turns a payment into income.
"""

from __future__ import annotations

from datetime import date

import pypdfium2 as pdfium
import pytest

from ledgerai.security.validators import ValidationError
from ledgerai.services.statements import extract_pages, parse_statement, verify_text_layer
from ledgerai.services.statements.extract import NoTextLayerError
from ledgerai.services.statements.layout import (
    group_lines,
    infer_columns,
    looks_like_amount,
    looks_like_date,
)
from ledgerai.services.statements.parse import parse_amount, parse_date
from ledgerai.services.statements.verify import (
    _INK_MIN_FRACTION,
    TokenCounts,
    _claimed_tokens,
    _ink_fraction,
    _within_budget,
)
from tests.synthetic_pdf import (
    DEFAULT_ROWS,
    STAMP,
    Run,
    summary_page,
    transaction_page,
    transposed_without_balance_statement,
    white_amount_statement,
    write_pdf,
)


def parse(data: bytes):
    return parse_statement(extract_pages(data))


class TestAmounts:
    @pytest.mark.parametrize(
        ("text", "cents"),
        [
            ("-42.10", -4210),
            ("42.10", 4210),
            ("(42.10)", -4210),
            ("42.10-", -4210),
            ("1,904.55", 190455),
            ("£1,234.56", 123456),
            ("42.10 CR", 4210),
            ("42.10 DR", -4210),
            ("−7.50", -750),
            ("+1800.00", 180000),
        ],
    )
    def test_printed_money_becomes_integer_cents(self, text: str, cents: int) -> None:
        assert parse_amount(text) == cents

    @pytest.mark.parametrize("text", ["", "abc", "4210", "12 Aug", "1.2.3", "42.1"])
    def test_things_that_are_not_money_are_refused(self, text: str) -> None:
        # A bare integer is the important one: a reference number is not an
        # amount, and treating it as one would invent transactions.
        assert parse_amount(text) is None

    def test_no_float_is_used(self) -> None:
        assert isinstance(parse_amount("0.10"), int)
        assert parse_amount("0.10") == 10


class TestDates:
    def test_a_full_date_needs_no_hint(self) -> None:
        assert parse_date("12/08/2026") == date(2026, 8, 12)
        assert parse_date("2026-08-12") == date(2026, 8, 12)

    def test_a_day_and_month_take_the_year_from_the_period(self) -> None:
        assert parse_date("12 Aug", year_hint=2026) == date(2026, 8, 12)
        assert parse_date("Aug 12", year_hint=2026) == date(2026, 8, 12)

    def test_a_day_and_month_without_a_hint_is_refused(self) -> None:
        # Guessing the current year would silently file a January statement
        # into the wrong year every January.
        assert parse_date("12 Aug") is None

    def test_an_impossible_date_is_refused(self) -> None:
        assert parse_date("31/02/2026") is None


class TestShapes:
    def test_amount_shapes(self) -> None:
        assert looks_like_amount("-42.10")
        assert looks_like_amount("1,904.55")
        assert not looks_like_amount("201847362")
        assert not looks_like_amount("SANDBOX GROCERS")

    def test_date_shapes(self) -> None:
        assert looks_like_date("12 Aug")
        assert looks_like_date("2026-08-12")
        assert not looks_like_date("SANDBOX")
        assert not looks_like_date("1,904.55")


class TestHappyPath:
    def test_a_simple_statement_reads_every_row(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        assert result.row_count == 5
        assert [r.amount_cents for r in result.rows] == [-4210, -275, -3036, -675, 180000]

    def test_the_period_and_currency_are_read_from_the_header(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        assert result.period_start == date(2026, 8, 1)
        assert result.period_end == date(2026, 8, 31)
        assert result.currency == "GBP"

    def test_the_year_comes_from_the_period(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        assert all(row.posted_date.year == 2026 for row in result.rows)

    def test_descriptions_survive_intact(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        assert result.rows[0].description == "SANDBOX GROCERS 0042"

    def test_every_row_is_confident_when_nothing_is_ambiguous(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        assert all(row.confidence == 1.0 for row in result.rows)


class TestBalanceChain:
    def test_an_intact_chain_is_reported_intact(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        assert result.balance_chain_checked
        assert result.balance_chain_ok

    def test_a_broken_chain_drops_confidence_on_the_rows_it_breaks(self) -> None:
        rows = list(DEFAULT_ROWS)
        rows[2] = ("14 Aug", "SANDBOX GROCERS 0042", -3036, 187_999)
        result = parse(write_pdf([transaction_page(rows)]))

        assert result.balance_chain_checked
        assert not result.balance_chain_ok
        assert "balance_chain_broken" in result.notes
        low = [r for r in result.rows if r.confidence <= 0.4]
        assert len(low) == 2, "the corrupted row and the one after it"

    def test_the_chain_settles_the_sign_of_unsigned_amounts(self) -> None:
        # Many statements print amounts unsigned and let the balance movement
        # say which way the money went.
        unsigned = [(d, desc, abs(amt), bal) for d, desc, amt, bal in DEFAULT_ROWS]
        result = parse(write_pdf([transaction_page(unsigned)]))

        assert [r.amount_cents for r in result.rows][1:] == [-275, -3036, -675, 180000]
        assert "sign_from_balance" in result.rows[1].notes

    def test_the_first_unsigned_row_is_flagged_rather_than_guessed(self) -> None:
        # There is no earlier balance to diff against, so its direction cannot
        # be recovered. Importing it at its printed sign would be a silent
        # guess on exactly one transaction a month.
        unsigned = [(d, desc, abs(amt), bal) for d, desc, amt, bal in DEFAULT_ROWS]
        result = parse(write_pdf([transaction_page(unsigned)]))

        first = result.rows[0]
        assert "sign_unresolved" in first.notes
        assert first.confidence <= 0.5

    def test_a_statement_without_balances_says_so(self) -> None:
        rows = [(d, desc, amt, None) for d, desc, amt, _ in DEFAULT_ROWS]
        result = parse(write_pdf([transaction_page(rows, balance_right=None)]))

        assert result.row_count == 5
        assert not result.balance_chain_checked
        assert "no_balance_column" in result.notes


class TestMultiPage:
    def test_pages_of_transactions_are_concatenated(self) -> None:
        more = [
            ("17 Aug", "SANDBOX HARDWARE", -1250, 365_219),
            ("18 Aug", "SANDBOX PHARMACY", -899, 364_320),
        ]
        result = parse(
            write_pdf(
                [
                    transaction_page(DEFAULT_ROWS),
                    summary_page(),
                    transaction_page(more, with_header=False),
                ]
            )
        )
        assert result.row_count == 7
        assert result.table_pages == 2

    def test_a_short_continuation_page_is_not_dropped(self) -> None:
        """The failure this guards against is invisible in the result.

        A page carrying the last two transactions of the month has too few rows
        to infer its own columns. Skipping it makes a short month look like a
        complete one to anybody checking totals.
        """
        tail = [("19 Aug", "SANDBOX FLORIST", -2200, 362_120)]
        result = parse(
            write_pdf([transaction_page(DEFAULT_ROWS), transaction_page(tail, with_header=False)])
        )
        assert result.row_count == 6
        assert result.rows[-1].description == "SANDBOX FLORIST"

    def test_a_summary_page_contributes_no_rows(self) -> None:
        assert parse(write_pdf([summary_page()])).row_count == 0

    def test_a_summary_page_beside_transactions_still_contributes_none(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS), summary_page()]))
        assert result.row_count == 5


class TestFailsClosed:
    def test_a_pdf_with_no_text_layer_is_refused(self) -> None:
        with pytest.raises(NoTextLayerError) as exc:
            parse(write_pdf([[]]))
        assert "csv" in str(exc.value).lower(), "the refusal must say what to do instead"

    def test_an_unopenable_file_is_refused(self) -> None:
        with pytest.raises(ValidationError):
            extract_pages(b"not a pdf at all")

    def test_a_page_over_the_cap_is_refused(self) -> None:
        pages = [transaction_page(DEFAULT_ROWS) for _ in range(41)]
        with pytest.raises(ValidationError) as exc:
            extract_pages(write_pdf(pages))
        assert "40" in str(exc.value)

    def test_a_page_of_prose_yields_nothing(self) -> None:
        prose = [
            Run(58, 700, "Terms and conditions apply to this account."),
            Run(58, 685, "Please contact us if you have any questions."),
            Run(58, 670, STAMP),
        ]
        assert parse(write_pdf([prose])).row_count == 0

    def test_lines_that_do_not_match_are_counted_not_guessed(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS)]))
        # Header lines are skipped rather than turned into rows.
        assert result.skipped_lines > 0
        assert result.row_count == 5


class TestTamperDetection:
    def _texts(self, data: bytes) -> list[str]:
        return [" ".join(w.text for w in page) for page in extract_pages(data)]

    def test_an_honest_statement_verifies(self) -> None:
        data = write_pdf([transaction_page(DEFAULT_ROWS)])
        result = verify_text_layer(data, self._texts(data))
        assert result.checked_pages == 1
        assert result.ok

    def test_money_in_the_text_layer_that_the_page_never_draws_is_caught(self) -> None:
        """The attack the text-layer approach introduces.

        A PDF's text layer and its rendering are independent, so a file can
        claim figures it never shows. Reading the text layer alone would import
        the claim.
        """
        data = write_pdf([transaction_page(DEFAULT_ROWS, invisible_extra=(600, -999_999))])
        result = verify_text_layer(data, self._texts(data))
        assert not result.ok
        assert "text_layer_disagrees_with_render" in result.notes

    def test_a_small_hidden_amount_is_caught_too(self) -> None:
        data = write_pdf([transaction_page(DEFAULT_ROWS, invisible_extra=(600, -1234))])
        assert not verify_text_layer(data, self._texts(data)).ok

    def test_a_white_on_white_amount_is_caught_although_its_row_renders(self) -> None:
        """The case that rules out judging a token by its neighbours.

        Only the amount is painted white. The date, description and balance on
        that row are drawn normally, so any test that asks "did this row
        render?" answers yes and lets the file through. What settles it is ink
        inside the amount's own box, of which there is none.
        """
        result = verify_text_layer(white_amount_statement(), None)
        assert not result.ok
        assert "page_no_ink" in result.notes

    def test_transposed_amounts_are_caught_without_a_balance_column(self) -> None:
        """Position is the evidence when arithmetic is unavailable.

        Both amounts are still on the page and every total is unchanged, so a
        set or multiset comparison sees nothing wrong, and there is no balance
        column to reconcile. Comparing each claimed token against the pixels at
        its own coordinates is what catches it.
        """
        result = verify_text_layer(transposed_without_balance_statement(), None)
        assert not result.ok
        assert "page_different_digits" in result.notes

    def test_every_page_is_checked_not_a_sample(self) -> None:
        """A tamper on a later page must not survive by being unlucky to sample."""
        pages = [transaction_page(DEFAULT_ROWS, with_header=(i == 0)) for i in range(4)]
        pages[2] = transaction_page(
            DEFAULT_ROWS, with_header=False, invisible_extra=(600, -777_777)
        )
        result = verify_text_layer(write_pdf(pages), None)
        assert result.checked_pages == 4
        assert not result.ok

    def test_an_honest_statement_does_not_pay_for_the_retry(self) -> None:
        """The higher-resolution pass is adaptive, not routine."""
        result = verify_text_layer(write_pdf([transaction_page(DEFAULT_ROWS)]), None)
        assert result.ok
        assert result.retried_pages == 0

    def test_results_do_not_vary_between_runs(self) -> None:
        data = white_amount_statement()
        verdicts = [
            (verify_text_layer(data, None).ok, tuple(verify_text_layer(data, None).notes))
            for _ in range(2)
        ]
        assert len(set(verdicts)) == 1


class TestInkEvidence:
    """Separating "OCR missed it" from "the page never drew it".

    These two look identical to a text comparison — nothing was read either way
    — and the whole verifier turns on telling them apart.
    """

    def _first_page(self, data: bytes) -> tuple[object, object, float, float]:
        document = pdfium.PdfDocument(data)
        page = document[0]
        _, height = page.get_size()
        scale = 200 / 72
        image = page.render(scale=scale).to_pil().convert("L")
        return document, image, height, scale

    def _boxes(self, document: object, index: int = 0) -> list:
        return _claimed_tokens(document, index)

    def test_drawn_glyphs_register_far_above_the_threshold(self) -> None:
        data = write_pdf([transaction_page(DEFAULT_ROWS)])
        document, image, height, scale = self._first_page(data)
        try:
            fractions = []
            for _token, left, bottom, right, top in self._boxes(document):
                region = (
                    left * scale,
                    (height - top) * scale,
                    right * scale,
                    (height - bottom) * scale,
                )
                fractions.append(_ink_fraction(image, region))
            assert fractions
            assert min(fractions) > _INK_MIN_FRACTION * 10
        finally:
            document.close()

    def test_a_white_painted_amount_registers_no_ink_at_all(self) -> None:
        document, image, height, scale = self._first_page(white_amount_statement())
        try:
            fractions = []
            for _token, left, bottom, right, top in self._boxes(document):
                region = (
                    left * scale,
                    (height - top) * scale,
                    right * scale,
                    (height - bottom) * scale,
                )
                fractions.append(_ink_fraction(image, region))
            blank = [value for value in fractions if value < _INK_MIN_FRACTION]
            inked = [value for value in fractions if value >= _INK_MIN_FRACTION]
            assert len(blank) == 1, "exactly one amount was painted white"
            # The two populations must not be adjacent: a threshold sitting in a
            # gap this wide is a classifier, not a tuning parameter.
            assert min(inked) > max(blank) * 100 or max(blank) == 0.0
        finally:
            document.close()


class TestVerifierBudget:
    """The omission budget, at its boundaries.

    Conflicts are never budgeted; only tokens the page demonstrably drew and OCR
    failed to read can be spent against it.
    """

    def _counts(self, **kwargs: int) -> TokenCounts:
        counts = TokenCounts(total=kwargs.pop("total", 100))
        for key, value in kwargs.items():
            setattr(counts, key, value)
        counts.matched = counts.total - counts.omitted - counts.conflicts
        return counts

    def test_a_single_conflict_fails_however_clean_the_rest_is(self) -> None:
        assert not _within_budget(self._counts(total=100, conflicts=1))

    def test_the_floor_admits_three_omissions_on_a_small_page(self) -> None:
        assert _within_budget(self._counts(total=20, omitted=3))
        assert not _within_budget(self._counts(total=20, omitted=4))

    def test_the_fraction_takes_over_on_a_large_page(self) -> None:
        assert _within_budget(self._counts(total=100, omitted=5))
        assert not _within_budget(self._counts(total=100, omitted=6))

    def test_coverage_below_the_floor_fails_closed(self) -> None:
        counts = TokenCounts(total=100, matched=85, omitted=0, conflicts=0)
        assert counts.coverage < 0.90
        assert not _within_budget(counts)


class TestLayoutVariants:
    def test_a_shifted_amount_column_still_resolves(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS, amount_right=430)]))
        assert result.row_count == 5

    def test_a_wider_date_column_still_resolves(self) -> None:
        result = parse(write_pdf([transaction_page(DEFAULT_ROWS, date_x=40, desc_x=160)]))
        assert result.row_count == 5

    def test_columns_cannot_be_inferred_from_a_single_row(self) -> None:
        # One row is not evidence of a column. Inferring geometry from it would
        # make every stray figure on a cover page look like a table.
        lines = group_lines(extract_pages(write_pdf([transaction_page(DEFAULT_ROWS[:1])]))[0])
        assert infer_columns(lines) is None


class TestFixturesAreSynthetic:
    def test_every_generated_page_carries_the_synthetic_stamp(self) -> None:
        """No real statement can enter this suite by accident."""
        for data in (
            write_pdf([transaction_page(DEFAULT_ROWS)]),
            write_pdf([summary_page()]),
            write_pdf([transaction_page(DEFAULT_ROWS, with_header=False)]),
        ):
            text = "\n".join(" ".join(w.text for w in page) for page in extract_pages(data))
            assert "SYNTHETIC" in text

    def test_the_stamp_says_it_is_not_real(self) -> None:
        assert "NOT A REAL STATEMENT" in STAMP
