"""unique system category slug

Revision ID: 3f5a019a2d69
Revises: 89a3a0c224fe
Create Date: 2026-08-26 17:36:29.457595
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3f5a019a2d69'
down_revision: str | None = '89a3a0c224fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_categories_system_slug', 'categories', ['slug'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_system_slug', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    # ### end Alembic commands ###
