"""receipts alerts and base currency

Revision ID: a67da4364dca
Revises: 6653fa455298
Create Date: 2026-08-26 20:32:04.963429
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'a67da4364dca'
down_revision: str | None = '6653fa455298'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('link_mode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=40), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('subtotal_cents', sa.BigInteger(), nullable=True),
    sa.Column('tax_cents', sa.BigInteger(), nullable=True),
    sa.Column('tip_cents', sa.BigInteger(), nullable=True),
    sa.Column('total_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ocr_confidence >= 0 AND ocr_confidence <= 1', name='ck_receipts_conf_range'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_index(op.f('ix_receipts_transaction_id'), 'receipts', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_index('ix_receipts_user_status', 'receipts', ['user_id', 'status'], unique=False)
    op.create_table('receipt_match_rejections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id', 'transaction_id', name='uq_receipt_rejection')
    )
    op.create_index(op.f('ix_receipt_match_rejections_receipt_id'), 'receipt_match_rejections', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipt_match_rejections_user_id'), 'receipt_match_rejections', ['user_id'], unique=False)
    # Existing rows need a value before these can be NOT NULL. server_default
    # backfills them in one statement; the ORM still supplies the value on
    # insert, so the default is a migration device, not application behaviour.
    op.add_column(
        'accounts',
        sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'users',
        sa.Column('base_currency', sa.String(length=3), nullable=False, server_default='USD'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_currency')
    op.drop_column('accounts', 'is_synthetic')
    op.drop_index(op.f('ix_receipt_match_rejections_user_id'), table_name='receipt_match_rejections')
    op.drop_index(op.f('ix_receipt_match_rejections_receipt_id'), table_name='receipt_match_rejections')
    op.drop_table('receipt_match_rejections')
    op.drop_index('ix_receipts_user_status', table_name='receipts')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_transaction_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
